## K-Means
***

In [5]:
import numpy as np
from numpy.typing import ArrayLike

In [6]:
x = np.array([(0,-6), (4,4), (0,0), (-5,2)])
z = np.array([(-5,2), (0,-6)])

# Number of clusters
k = len(z)
# Dimensionality of data points
dim = 2

In [7]:
def get_distance(x: ArrayLike, center: ArrayLike, l_norm: int = 2) -> ArrayLike:
    """
    Returns an nd array of distances, between each point of x to center. Each
    row shows distances for every x given a z.
    """
    rows, cols = len(center), len(x)
    distance = np.zeros((rows, cols))

    for row in range(rows):
        distance[row] = np.sum(np.power(np.abs(x-center[row]), l_norm), axis=1)

    return distance


def get_cluster(distances: ArrayLike) -> ArrayLike:
    """Returns an array with the cluster number closest to each x."""
    
    return np.argmin(distances, axis=0)


def get_medoid(x: ArrayLike, assignments: ArrayLike, cluster: int, l_norm: int) -> ArrayLike:
    """Comment this."""

    x_i = x[assignments==cluster]
    
    distances = get_distance(x=x_i, center=x, l_norm=l_norm)
    medoid_idx = np.argmin(np.sum(distances, axis=1))
    medoid = x[medoid_idx]

    return medoid


def get_medoids(x: ArrayLike, assignments: ArrayLike, l_norm: int, k:int, dim:int) -> ArrayLike:
    """Comment this."""

    med = np.zeros((k, dim))
    for i in range(k):
        med[i] = get_medoid(x=x, assignments=assignments, cluster=i, l_norm=l_norm)

    return med


def get_centroids(x: ArrayLike, assignments: ArrayLike, k: int, dim: int) -> ArrayLike:
    
    centroid = np.zeros((k, dim))

    for i in range(k):
        x_i = x[assignments==i]
        centroid[i] = np.median(x_i, axis=0)

    return centroid


In [8]:
for i in range(5):
    distances = get_distance(x=x, center=z, l_norm=1)
    print("\n Distances:")
    print(distances)
    
    assignments = get_cluster(distances)
    print("\n Assignments:")
    print(assignments)
    z = get_centroids(x=x, assignments=assignments, k=k, dim=dim)
    print("\n New medoids:")
    print(z)


 Distances:
[[13. 11.  7.  0.]
 [ 0. 14.  6. 13.]]

 Assignments:
[1 0 1 0]

 New medoids:
[[-0.5  3. ]
 [ 0.  -3. ]]

 Distances:
[[ 9.5  5.5  3.5  5.5]
 [ 3.  11.   3.  10. ]]

 Assignments:
[1 0 1 0]

 New medoids:
[[-0.5  3. ]
 [ 0.  -3. ]]

 Distances:
[[ 9.5  5.5  3.5  5.5]
 [ 3.  11.   3.  10. ]]

 Assignments:
[1 0 1 0]

 New medoids:
[[-0.5  3. ]
 [ 0.  -3. ]]

 Distances:
[[ 9.5  5.5  3.5  5.5]
 [ 3.  11.   3.  10. ]]

 Assignments:
[1 0 1 0]

 New medoids:
[[-0.5  3. ]
 [ 0.  -3. ]]

 Distances:
[[ 9.5  5.5  3.5  5.5]
 [ 3.  11.   3.  10. ]]

 Assignments:
[1 0 1 0]

 New medoids:
[[-0.5  3. ]
 [ 0.  -3. ]]
